apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-tag
  annotations:
    description: |
      Generate a new unique image tag based on format YYYY-MM-YY-HH-MM-SS.
spec:
  params:
    - name: SHA
      description: The git commit sha to include in the image tag name
  results:
    - name: image-tag
      description: The tag in the format of ${git-sha}-${model-version}-${date}
  steps:
    - name: generate-image-tag
      image: registry.access.redhat.com/ubi8/ubi-minimal:8.3
      script: |
        #!/usr/bin/env sh
        set -e

        # get the git sha
        sha=$(echo $(params.SHA) | cut -c1-7)

        # get the ml-model version
        model_version="1"

        # generate the current date/time
        date=$(date +"%Y%m%d-%H%M%S")

        tag=${sha}-${model_version}-${date}

        echo ${tag}
        echo ${tag} > $(results.image-tag.path)
