apiVersion: v2
name: kafdrop
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

dependencies:
  - name: "kafdrop"
    version: "0.1.0"
    repository: "https://rh-intelligent-application-practice.github.io/helm-charts/"
