apiVersion: v2
name: odh
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

dependencies:
  - name: "odh"
    version: "0.3.1"
    repository: "https://strangiato.github.io/helm-charts/"
