apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: {{ include "iris-inference-service.fullname" . }}
  labels:
    {{- include "iris-inference-service.labels" . | nindent 4 }}
spec:
  name: {{ include "iris-inference-service.name" . }}
  predictors:
    - componentSpecs:
        - spec:
            {{- with .Values.imagePullSecrets }}
            imagePullSecrets:
                {{- toYaml . | nindent 8 }}
            {{- end }}
            serviceAccountName: {{ include "iris-inference-service.serviceAccountName" . }}
            securityContext:
              {{- toYaml .Values.podSecurityContext | nindent 14 }}
            containers:
              - name: classifier
                image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
                imagePullPolicy: {{ .Values.image.pullPolicy }}    
                resources:
                    {{- toYaml .Values.resources | nindent 20 }}
                livenessProbe:
                    failureThreshold: 3
                    initialDelaySeconds: 10
                    periodSeconds: 5
                    successThreshold: 1
                    httpGet:
                        path: /health/status
                        port: http
                        scheme: HTTP
                        timeoutSeconds: 1
                readinessProbe:
                    failureThreshold: 3
                    initialDelaySeconds: 10
                    periodSeconds: 5
                    successThreshold: 1
                    httpGet:
                        path: /health/status
                        port: http
                        scheme: HTTP
      graph:
        children: []
        name: classifier
        type: MODEL
      name: {{ include "iris-inference-service.name" . }}
      replicas: {{ .Values.replicaCount }}
